import { createHash } from 'node:crypto';
import { existsSync } from 'node:fs';
import { access, mkdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';

const publicOrigin = (process.env.PUBLIC_SITE_ORIGIN || 'https://wild-and-the-sun.pages.dev').replace(/\/+$/, '');
// Search engines stay out until the owner approves launch. Set SITE_INDEXABLE=true then.
const indexable = process.env.SITE_INDEXABLE === 'true';
const squareUrl = 'https://wild-and-the-sun.square.site/s/order#most-popular';
const instagramUrl = 'https://www.instagram.com/wild_and_the_sun_acai_cafe/';
const venueNamePattern = /wild.*sun/i;

// The Wild and The Sun CentralPass backend origin, e.g. https://api.wildandthesun.com.au
// The site reads venue details, hours and bookings from it. Leave it empty to
// build with src/venue.json and the phone-booking fallback. Never point this at
// another venue's backend.
const centralpassApiBase = (process.env.CENTRALPASS_API_BASE || '').trim().replace(/\/+$/, '');
if (centralpassApiBase) {
  const url = new URL(centralpassApiBase);
  const local = ['localhost', '127.0.0.1'].includes(url.hostname);
  if (url.protocol !== 'https:' && !(local && url.protocol === 'http:')) throw new Error('CENTRALPASS_API_BASE must use HTTPS.');
  if (url.pathname !== '/' || url.search || url.hash) throw new Error('CENTRALPASS_API_BASE must be an origin only, without /api.');
}

// Preview builds can show the booking form with sample data (booking-demo.js)
// before the venue's backend exists. Never used when a real backend is set.
const bookingDemo = process.env.BOOKING_DEMO === 'true' && !centralpassApiBase;

const pages = [
  { slug: '', key: 'home', title: 'Wild and The Sun Açaí Cafe | Aberfoyle Park', description: 'Açaí, specialty drinks and good coffee at Wild and The Sun, a family café at Aberfoyle Hub. Book a table online or order ahead.', image: '/assets/client/acai-trio.jpg', structuredData: true },
  { slug: 'menu', key: 'menu', title: 'Menu | Wild and The Sun Açaí Cafe', description: 'View the Wild and The Sun café menu in Aberfoyle Park. Order current items online through the café’s Square store.', image: '/assets/client/berry-choc.jpg' },
  { slug: 'visit', key: 'visit', title: 'Visit Us | Wild and The Sun, Aberfoyle Park', description: 'Meet the family behind Wild and The Sun, plan a group catch-up, and find our address and opening hours at Aberfoyle Hub.', image: '/assets/graphic/family-instagram.webp' },
  { slug: 'book', key: 'book', title: 'Book a Table | Wild and The Sun Açaí Cafe', description: 'Book a table at Wild and The Sun in Aberfoyle Park. Check live availability and reserve online, or call the café.', image: '/assets/client/specialty-pair.jpg', scripts: (bookingDemo ? '<script src="/booking-demo.js?v={{VERSION}}" defer></script>' : '') + '<script src="/booking.js?v={{VERSION}}" defer></script>' },
];

// Older pages were folded into Visit us. Keep their URLs working.
const redirects = [
  { slug: 'story', to: '/visit/#story' },
  { slug: 'venue-hire', to: '/visit/#gather' },
];

const configJs = '// Generated by build.mjs from CENTRALPASS_API_BASE. Change that variable and rebuild; do not edit this file.\nwindow.WILD_SUN_CONFIG = Object.freeze({ centralpassApiBase: ' + JSON.stringify(centralpassApiBase) + ' });\n';
// Cache-busting version from the shipped CSS/JS, so an unchanged rebuild
// produces identical pages and does not dirty the committed build output.
const shippedCode = await Promise.all(['design.css', 'site.js', 'venue.js', 'booking.js', ...(bookingDemo ? ['booking-demo.js'] : [])].map((file) => readFile(file, 'utf8')));
const version = createHash('sha256').update(configJs).update(shippedCode.join('\n')).digest('hex').slice(0, 10);
const dayNames = ['Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'];

function escapeHtml(value) {
  return String(value).replace(/[&<>"']/g, (character) => ({
    '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;',
  })[character]);
}

function clockTime(value) {
  const match = /^([01]\d|2[0-3]):([0-5]\d)/.exec(String(value || ''));
  return match ? match[1] + ':' + match[2] : null;
}

function displayTime(value) {
  const [h, m] = value.split(':').map(Number);
  return String(h % 12 || 12) + (m ? ':' + String(m).padStart(2, '0') : '') + (h >= 12 ? 'pm' : 'am');
}

function normaliseHours(rows) {
  if (!Array.isArray(rows)) return null;
  const byDay = new Map();
  for (const row of rows) {
    const day = Number(row.day_of_week);
    if (!Number.isInteger(day) || day < 0 || day > 6) continue;
    const open = clockTime(row.open_time);
    const close = clockTime(row.close_time);
    byDay.set(day, row.is_open && open && close ? { day_of_week: day, is_open: true, open_time: open, close_time: close } : { day_of_week: day, is_open: false, open_time: null, close_time: null });
  }
  return byDay.size === 7 ? [0, 1, 2, 3, 4, 5, 6].map((day) => byDay.get(day)) : null;
}

async function getJson(path) {
  const controller = new AbortController();
  const timeout = setTimeout(() => controller.abort(), 10000);
  try {
    const response = await fetch(centralpassApiBase + path, { headers: { Accept: 'application/json' }, signal: controller.signal });
    if (!response.ok) throw new Error(path + ' returned ' + response.status);
    return await response.json();
  } finally {
    clearTimeout(timeout);
  }
}

// Venue details come from the CentralPass admin portal (Settings > Venue) and
// hours from its Hours page. src/venue.json is only the offline fallback.
async function loadVenue() {
  const fallback = JSON.parse(await readFile('src/venue.json', 'utf8'));
  const venue = { name: fallback.name, phone: fallback.phone, address: fallback.address, email: fallback.email || null, abn: fallback.abn || null, hours: normaliseHours(fallback.hours) };
  if (!venue.hours) throw new Error('src/venue.json needs seven valid hours rows.');
  if (!centralpassApiBase) return { venue, source: 'src/venue.json' };
  let settings;
  try {
    settings = await getJson('/api/settings/public');
  } catch (error) {
    console.warn('Warning: could not read venue details from CentralPass (' + error.message + '). Using src/venue.json; the live site refreshes them in the browser.');
    return { venue, source: 'src/venue.json (CentralPass unreachable)' };
  }
  if (!venueNamePattern.test(String(settings.restaurant_name || ''))) {
    throw new Error('CENTRALPASS_API_BASE belongs to "' + settings.restaurant_name + '", not Wild and The Sun. Refusing to build with another venue’s details.');
  }
  const text = (value) => (typeof value === 'string' && value.trim() ? value.trim() : null);
  venue.name = text(settings.restaurant_name) || venue.name;
  for (const key of ['phone', 'address']) {
    if (text(settings[key])) venue[key] = text(settings[key]);
    else console.warn('Warning: the admin portal has no venue ' + key + '; using src/venue.json.');
  }
  // Optional fields follow the admin exactly: blank there means hidden here.
  venue.email = text(settings.email);
  venue.abn = text(settings.abn);
  if (settings.features?.hours !== false) {
    try {
      const hours = normaliseHours((await getJson('/api/settings/hours')).store_hours);
      if (hours) venue.hours = hours;
      else console.warn('Warning: CentralPass hours were incomplete; using src/venue.json hours.');
    } catch (error) {
      console.warn('Warning: could not read CentralPass hours (' + error.message + '); using src/venue.json hours.');
    }
  }
  return { venue, source: 'CentralPass admin portal' };
}

const { venue, source: venueSource } = await loadVenue();

const telHref = 'tel:' + venue.phone.replace(/[^0-9+]/g, '');
const directionsUrl = 'https://www.google.com/maps/dir/?api=1&destination=' + encodeURIComponent(venue.name + ', ' + venue.address);
const addressLines = venue.address.split(/\s*[\n,]\s*/).filter(Boolean);

// Monday first for reading. venue.js highlights today and refreshes the rows.
const hoursList = [1, 2, 3, 4, 5, 6, 0].map((index) => {
  const row = venue.hours[index];
  const time = row.is_open ? displayTime(row.open_time) + ' – ' + displayTime(row.close_time) : 'Closed';
  return '<li data-day="' + index + '"><span>' + dayNames[index] + '</span><strong>' + time + '</strong></li>';
}).join('');

// Group matching neighbours: "Tue – Sat 9am – 5pm · Sun 9am – 2pm · Mon closed".
function hoursSummary(hours) {
  const order = [1, 2, 3, 4, 5, 6, 0];
  const label = (row) => (row.is_open ? displayTime(row.open_time) + ' – ' + displayTime(row.close_time) : 'closed');
  const groups = [];
  for (const day of order) {
    const text = label(hours[day]);
    const last = groups[groups.length - 1];
    if (last && last.text === text) last.to = day;
    else groups.push({ from: day, to: day, text });
  }
  const short = (day) => dayNames[day].slice(0, 3);
  return groups.map((group) => (group.from === group.to ? short(group.from) : short(group.from) + ' – ' + short(group.to)) + ' ' + group.text).join(' · ');
}

const venueJson = JSON.stringify({ name: venue.name, phone: venue.phone, address: venue.address, email: venue.email, abn: venue.abn, hours: venue.hours }).replace(/</g, '\\u003c');

function structuredData() {
  const match = /^(.*?),\s*([^,]+?)\s+(SA|NSW|VIC|QLD|WA|TAS|NT|ACT)\s+(\d{4})$/i.exec(venue.address.replace(/\s*\n\s*/g, ', '));
  const address = match
    ? { '@type': 'PostalAddress', streetAddress: match[1], addressLocality: match[2], addressRegion: match[3].toUpperCase(), postalCode: match[4], addressCountry: 'AU' }
    : { '@type': 'PostalAddress', streetAddress: venue.address, addressCountry: 'AU' };
  const data = {
    '@context': 'https://schema.org',
    '@type': 'CafeOrCoffeeShop',
    name: venue.name,
    url: publicOrigin + '/',
    image: [publicOrigin + '/assets/client/acai-trio.jpg', publicOrigin + '/assets/graphic/family-instagram.webp'],
    telephone: venue.phone,
    ...(venue.email ? { email: venue.email } : {}),
    ...(venue.abn ? { taxID: venue.abn } : {}),
    address,
    servesCuisine: ['Açaí', 'Coffee', 'Smoothies'],
    menu: publicOrigin + '/menu/',
    acceptsReservations: true,
    sameAs: [instagramUrl],
    openingHoursSpecification: venue.hours.filter((row) => row.is_open).map((row) => ({
      '@type': 'OpeningHoursSpecification', dayOfWeek: 'https://schema.org/' + dayNames[row.day_of_week], opens: row.open_time, closes: row.close_time,
    })),
  };
  return '<script type="application/ld+json">' + JSON.stringify(data).replace(/</g, '\\u003c') + '</script>';
}

// Photos ship as responsive WebP (560, 800 and full width) with the original
// file as the fallback. Templates can set data-sizes for small placements.
function responsiveImages(html) {
  return html.replace(/<img\b[^>]*\ssrc="\/assets\/(client|graphic)\/([\w-]+)\.(jpg|webp)"[^>]*>/g, (tag, folder, name) => {
    const base = '/assets/' + folder + '/' + name;
    const full = name === 'family-instagram' ? 1100 : 1122;
    const widths = [560, 800, full];
    if (!widths.every((width) => existsSync('.' + base + '-' + width + '.webp'))) return tag;
    const sizes = /data-sizes="([^"]+)"/.exec(tag)?.[1] || '(max-width: 900px) 92vw, 46vw';
    const img = tag.replace(/\s*data-sizes="[^"]+"/, '');
    return '<picture><source type="image/webp" srcset="' + widths.map((width) => base + '-' + width + '.webp ' + width + 'w').join(', ') + '" sizes="' + sizes + '" />' + img + '</picture>';
  });
}

const [layout, nav, footer] = await Promise.all([
  readFile('src/layout.html', 'utf8'),
  readFile('src/nav.html', 'utf8'),
  readFile('src/footer.html', 'utf8'),
]);

const hardCodedVenue = /0451 661 351|\+61451661351|130-150 Hub Drive/;
for (const [name, source] of [['layout', layout], ['nav', nav], ['footer', footer]]) {
  if (hardCodedVenue.test(source)) throw new Error('Hard-coded venue details in src/' + name + '.html. Use the {{VENUE_*}} markers.');
}

const venueMarkers = {
  VENUE_NAME: escapeHtml(venue.name),
  VENUE_PHONE: escapeHtml(venue.phone),
  VENUE_TEL: escapeHtml(telHref),
  VENUE_ADDRESS: escapeHtml(venue.address.replace(/\s*\n\s*/g, ', ')),
  VENUE_ADDRESS_LINES: addressLines.map(escapeHtml).join('<br />'),
  VENUE_DIRECTIONS: escapeHtml(directionsUrl),
  VENUE_ABN: escapeHtml(venue.abn || ''),
  VENUE_ABN_HIDDEN: venue.abn ? '' : 'hidden',
  VENUE_EMAIL: escapeHtml(venue.email || ''),
  VENUE_MAILTO: escapeHtml(venue.email ? 'mailto:' + venue.email : ''),
  VENUE_EMAIL_HIDDEN: venue.email ? '' : 'hidden',
  VENUE_JSON: venueJson,
  HOURS_LIST: hoursList,
  HOURS_SUMMARY: escapeHtml(hoursSummary(venue.hours)),
  BOOKING_CARD_CLASS: centralpassApiBase || bookingDemo ? ' is-connecting' : '',
  SQUARE_URL: squareUrl,
  INSTAGRAM_URL: instagramUrl,
  VERSION: version,
};

for (const page of pages) {
  const body = await readFile(join('src', 'pages', page.key + '.html'), 'utf8');
  const canonicalUrl = publicOrigin + '/' + (page.slug ? page.slug + '/' : '');
  const activeNav = nav.split('data-nav="' + page.key + '"').join('data-nav="' + page.key + '" aria-current="page"');
  const replacements = {
    TITLE: escapeHtml(page.title),
    DESCRIPTION: escapeHtml(page.description),
    OG_IMAGE: escapeHtml(publicOrigin + page.image),
    OG_URL: escapeHtml(canonicalUrl),
    CANONICAL: '<link rel="canonical" href="' + escapeHtml(canonicalUrl) + '" />',
    HEAD_EXTRA: page.structuredData ? structuredData() : '',
    PAGE: page.key,
    NAV: activeNav,
    FOOTER: footer,
    BODY: body,
    PAGE_SCRIPTS: page.scripts || '',
    ...venueMarkers,
  };
  let html = layout;
  // Two passes so markers inside NAV, FOOTER, BODY and PAGE_SCRIPTS resolve too.
  for (let pass = 0; pass < 2; pass += 1) {
    for (const [key, value] of Object.entries(replacements)) html = html.split('{{' + key + '}}').join(value);
  }
  html = responsiveImages(html.replace(/^[ \t]+$/gm, ''));
  if (html.includes('{{')) throw new Error('Unresolved template marker in ' + page.key + ': ' + html.match(/\{\{[A-Z_]+\}\}/)?.[0]);
  if ((html.match(/<h1\b/g) || []).length !== 1) throw new Error('Expected one H1 in ' + page.key);
  if (hardCodedVenue.test(body)) throw new Error('Hard-coded venue details in src/pages/' + page.key + '.html. Use the {{VENUE_*}} markers.');
  if (page.key === 'menu' && (!html.includes('menu-preview.svg') || /MENU PREVIEW · COMING SOON|Menu selection coming soon/.test(html))) {
    throw new Error('Menu image is missing or the old placeholder returned.');
  }
  const destination = page.slug ? join(page.slug, 'index.html') : 'index.html';
  if (page.slug) await mkdir(page.slug, { recursive: true });
  await writeFile(destination, html, 'utf8');
}

for (const redirect of redirects) {
  const target = escapeHtml(redirect.to);
  const canonical = escapeHtml(publicOrigin + redirect.to.split('#')[0]);
  await mkdir(redirect.slug, { recursive: true });
  await writeFile(join(redirect.slug, 'index.html'), '<!doctype html><html lang="en-AU"><head><meta charset="utf-8"><meta name="robots" content="noindex"><title>Wild and The Sun</title><link rel="canonical" href="' + canonical + '"><meta http-equiv="refresh" content="0; url=' + target + '"></head><body><p><a href="' + target + '">Continue to Visit us</a></p></body></html>\n', 'utf8');
}

await writeFile('config.js', configJs, 'utf8');

for (const asset of ['assets/menu-preview.svg', 'assets/brand/logo-wordmark.png', 'assets/brand/logo-mark.png', 'assets/brand/favicon-64.png', 'assets/client/acai-trio.jpg', 'config.js', 'venue.js', 'site.js', 'booking.js', 'design.css', ...(bookingDemo ? ['booking-demo.js'] : [])]) {
  await access(asset);
}

// Security headers for Cloudflare Pages. The CSP allows scripts only from this
// site plus the one inline bootstrap line, and network calls only to this site
// and the CentralPass API.
const inlineScripts = [...layout.matchAll(/<script>([\s\S]*?)<\/script>/g)].map((match) => "'sha256-" + createHash('sha256').update(match[1]).digest('base64') + "'");
const csp = [
  "default-src 'self'",
  "script-src 'self' " + inlineScripts.join(' '),
  "style-src 'self' https://fonts.googleapis.com",
  "font-src https://fonts.gstatic.com",
  "img-src 'self' data:",
  "connect-src 'self'" + (centralpassApiBase ? ' ' + centralpassApiBase : ''),
  "frame-ancestors 'none'",
  "base-uri 'self'",
  "form-action 'self'",
  "object-src 'none'",
].join('; ');
const headers = ['/*',
  '  Content-Security-Policy: ' + csp,
  '  X-Content-Type-Options: nosniff',
  '  X-Frame-Options: DENY',
  '  Referrer-Policy: strict-origin-when-cross-origin',
  '  Permissions-Policy: camera=(), microphone=(), geolocation=(), payment=()',
  ...(indexable ? [] : ['  X-Robots-Tag: noindex']),
  '',
  '/assets/*',
  '  Cache-Control: public, max-age=604800',
  ''].join('\n');
await writeFile('_headers', headers, 'utf8');
await writeFile('robots.txt', 'User-agent: *\nAllow: /\nSitemap: ' + publicOrigin + '/sitemap.xml\n', 'utf8');

const urls = pages.map((page) => '  <url><loc>' + escapeHtml(publicOrigin + '/' + (page.slug ? page.slug + '/' : '')) + '</loc></url>').join('\n');
await writeFile('sitemap.xml', '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n' + urls + '\n</urlset>\n', 'utf8');

await writeFile('404.html', '<!doctype html><html lang="en-AU"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex"><title>Page not found | Wild and The Sun</title><link rel="icon" href="/assets/brand/favicon-64.png" type="image/png"><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,400..700&amp;family=Fraunces:ital,opsz,wght,SOFT@0,9..144,300..600,0..100;1,9..144,300..600,0..100&amp;display=swap" rel="stylesheet"><link rel="stylesheet" href="/design.css?v=' + version + '"></head><body class="page-404"><main class="not-found"><div class="sun sun-static" aria-hidden="true"></div><p class="eyebrow">Page not found</p><h1>Lost your <em>way?</em></h1><p>Let’s get you back to the good stuff.</p><a class="btn btn-primary" href="/">Go to the homepage</a></main></body></html>\n', 'utf8');

console.log('Built ' + pages.length + ' pages. Venue details and hours from ' + venueSource + '. ' + (centralpassApiBase ? 'Live CentralPass bookings at ' + centralpassApiBase + '.' : bookingDemo ? 'PREVIEW booking demo with sample data (BOOKING_DEMO=true).' : 'No CENTRALPASS_API_BASE: phone-booking fallback.'));
