window.WILD_SUN_MENU = [
  { id: 'seasonal', number: '01', title: 'Winter specials', subtitle: 'A little extra comfort while the weather is cool.', items: [
    { name: 'Waffles', price: '$17.00', description: 'Vanilla ice cream, whipped cream, fresh fruit, chocolate chips and Nutella.' },
    { name: 'Loaded Banana Bread', price: '$15.50', description: 'Moist banana bread piled with wholesome toppings for breakfast or a midday treat.' },
    { name: 'Peppermint Mocha', price: '$7.50', description: 'A rich, creamy mocha with a cool peppermint finish.' },
    { name: 'Banana Bread Matcha', price: '$8.00', description: 'Banana bread matcha, served hot or cold.' },
  ]},
  { id: 'acai', number: '02', title: 'Açaí bowl', subtitle: 'The one that started it all.', items: [
    { name: 'Classic Açaí Bowl', price: '$18.80', description: 'Açaí with granola, honey and fresh fruit.' },
  ]},
  { id: 'coffee', number: '03', title: 'Coffee and tea', subtitle: 'The familiar favourites, made with care.', items: [
    { name: 'Cappuccino', price: '$6.00', description: 'Espresso with velvety milk and a generous cap of foam.' },
    { name: 'Latte', price: '$6.00', description: 'Smooth espresso and steamed milk.' },
    { name: 'Tea', price: '$5.00', description: 'Steeped to order.' },
    { name: 'Espresso', price: '$5.50', description: 'A short, rich coffee shot.' },
    { name: 'Long Black', price: '$5.50', description: 'Espresso lengthened with hot water.' },
    { name: 'Macchiato', price: '$5.50', description: 'Espresso marked with a little frothed milk.' },
    { name: 'Flat White', price: '$6.00', description: 'Espresso with smooth, finely textured milk.' },
    { name: 'Mocha', price: '$6.50', description: 'Coffee with a chocolate twist.' },
  ]},
  { id: 'specialty-hot', number: '04', title: 'Specialty hot drinks', subtitle: 'Playful flavours, warm cups.', items: [
    { name: 'Pistachio Latte', price: '$8.50', description: 'A creamy latte infused with pistachio.', note: 'Contains nuts' },
    { name: 'Hot Chocolate', price: '$7.50', description: 'Rich, creamy and made to warm your day.' },
    { name: 'Turmeric Latte', price: '$7.50', description: 'A comforting milk drink with turmeric.' },
    { name: 'Spiced Latte', price: '$7.50', description: 'Aromatic milk with a gentle hint of spice.' },
    { name: 'Matcha Latte', price: '$8.50', description: 'Matcha powder whisked with steamed milk.' },
    { name: 'Cookie Butter Latte', price: '$8.50', description: 'A creamy latte infused with cookie butter.' },
  ]},
  { id: 'specialty-cold', number: '05', title: 'Specialty cold drinks', subtitle: 'Cold, colourful and a little unexpected.', items: [
    { name: 'Iced Strawberry Latte', price: '$9.50', description: 'Creamy iced latte with strawberry syrup.' },
    { name: 'Iced Pistachio', price: '$10.50', description: 'A pistachio-flavoured cold drink.', note: 'Contains nuts' },
    { name: 'Iced Peach Tea', price: '$7.50', description: 'Refreshing peach tea poured over ice.' },
    { name: 'Iced Chai', price: '$7.50', description: 'Black tea and spices, served chilled.' },
    { name: 'Iced Turmeric Latte', price: '$8.50', description: 'A creamy iced milk drink with turmeric.' },
    { name: 'Iced Spiced Latte', price: '$8.50', description: 'A creamy cold latte with warm spices.' },
    { name: 'Iced Coffee', price: '$12.00', description: 'Smooth coffee over ice with ice cream.' },
    { name: 'Iced Cookie Butter Latte', price: '$10.50', description: 'A chilled latte infused with cookie butter.' },
    { name: 'Pistachio Affogato', price: '$9.00', description: 'Ice cream, hot espresso and pistachio butter.', note: 'Contains nuts' },
    { name: 'Unicorn Frappe', price: '$14.00', description: 'Ice cream, milk and blue heaven flavour, finished with whipped cream and sprinkles.' },
    { name: 'Lychee Strawberry', price: '$14.00', description: 'Lychee and strawberry syrups with a bright lemon base.' },
  ]},
  { id: 'patisserie', number: '06', title: 'Pâtisserie and savouries', subtitle: 'Flaky, toasty, sweet and ready for lunch.', items: [
    { name: 'Ham, Cheese and Spinach Croissant', price: '$14.00', description: 'A flaky croissant filled with spinach, ham and three cheeses.' },
    { name: 'Veggie Croissant', price: '$14.00', description: 'Green leaves, tomato, cheese, cucumber and carrot.' },
    { name: 'Coconut Bite', price: '$3.20', description: 'One coconut bite.' },
    { name: 'Brownie Bite', price: '$3.50', description: 'One brownie bite.' },
    { name: 'Flower Baklava', price: '$7.80', description: 'Layered pastry filled with nuts.', note: 'Contains nuts' },
    { name: 'Gourmet Sando', price: '$18.00', description: 'Salami or ham, green salad, three cheeses and a house-made sauce.' },
    { name: 'Banana Bread', price: '$7.00', description: 'Soft, moist and full of classic banana flavour.' },
    { name: 'Quesadilla', price: '$23.00', description: 'Shredded chicken, minced beef or vegetables with melted cheese, folded in a warm tortilla and served with the creamy house sauce.' },
  ]},
  { id: 'smoothies', number: '07', title: 'Smoothies', subtitle: 'Fruit-forward, blended fresh.', items: [
    { name: 'Green Smoothie', price: '$14.00', description: 'Banana, spinach, mango, peanut butter, orange juice, chia seeds and yoghurt.', note: 'Contains peanuts and dairy' },
    { name: 'Berry Smoothie', price: '$14.00', description: 'Raspberries, blueberries, strawberries and coconut milk.' },
    { name: 'Tropical Smoothie', price: '$14.00', description: 'Mango, pineapple, banana, fruit juice and yoghurt.', note: 'Contains dairy' },
  ]},
  { id: 'fridge', number: '08', title: 'From the fridge', subtitle: 'Easy extras for the road.', items: [
    { name: '600 ml Water', price: '$3.80' },
    { name: '375 ml Coke Zero', price: '$3.80' },
    { name: '375 ml Coke', price: '$3.80' },
    { name: '250 ml Orange Juice Box', price: '$3.80' },
    { name: '250 ml Apple Juice Box', price: '$3.80' },
  ]},
];
